@Api_HostAddress = http://localhost:5032

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Api_HostAddress}}/account/admin/register
Content-Type: application/json

{
  "dateOfBirth": "2025-02-12T05:44:43.584Z",
  "phoneNumber": "string",
  "password": "QUqkhxH8KYhVs@fJ",
  "userName": "string",
  "email": "string@gmail.com",
  "firstName": "string",
  "middleName": "string",
  "lastName": "string",
  "profileImageUrl": "string"
}

###
POST {{Api_HostAddress}}/account/admin/login
Content-Type: application/json

{
  "userName": "ST/2024/444",
  "password": "sv+4Fn6+VK2GU5W!"
}

###

###
GET {{Api_HostAddress}}/students/exams
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU1QvMjAyNC80NDQiLCJpYXQiOiIxNzM5NTc5NzM5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIwNWFlODllMy1lODljLTRjNzktOTNiNC1iMTY5ODkzNGJhYzUiLCJqdGkiOiJjZDRkNTBkYi0xMDI1LTQyZTctOWE2ZS01NGY4YzdhMWM2YTciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiZXhwIjoxNzM5NTgwMDM5LCJpc3MiOiJTY2hvb2xFZGdlQ0JUQmFja2VuZEFQSSIsImF1ZCI6IlNQQUFuZE1vYmlsZUFwcCJ9.e-l8TvuBQSNtAFuQ_04MOjVUE1l7kPND1j0HMYR52Hw

###
GET {{Api_HostAddress}}/students/exams/results/005ad189-073d-4fd7-980d-54ffa7ed3954
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU1QvMjAyNC80NDQiLCJpYXQiOiIxNzM5NTc5NzM5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIwNWFlODllMy1lODljLTRjNzktOTNiNC1iMTY5ODkzNGJhYzUiLCJqdGkiOiJjZDRkNTBkYi0xMDI1LTQyZTctOWE2ZS01NGY4YzdhMWM2YTciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiZXhwIjoxNzM5NTgwMDM5LCJpc3MiOiJTY2hvb2xFZGdlQ0JUQmFja2VuZEFQSSIsImF1ZCI6IlNQQUFuZE1vYmlsZUFwcCJ9.e-l8TvuBQSNtAFuQ_04MOjVUE1l7kPND1j0HMYR52Hw
